name: cronjob
on:
 schedule:
   -cron: '* * * * *'

   jobs:
   cron:
   runs-on: ubuntu-latest
   steps:
   - name: clone repro
    uses: actions/checkout@v3 

   - name: setup python
    uses: actions/setup-python@v4
    with:          #with rwpresent the version of python 
     python-version: '3.10'

  - name: Run a pay script
    run: python 01hello.py